version: "3.7"
services:
  proxy:
    build: ./
    ports:
      - "3307:3307"
    depends_on:
      - "db"
    restart: always
  db:
    image: mysql:latest
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - ./mysqlconf:/etc/mysql/conf.d
