version: "1"
services:
  proxy:
    build: ./
    links:
      - db
    ports:
      - "3307:3307"

  db:
    image: mysql:5.7
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root

    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro
