"""More models for posts and groups

Revision ID: a650a07306d4
Revises: 4d38a8bad655
Create Date: 2020-07-19 19:22:08.397953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a650a07306d4'
down_revision = '4d38a8bad655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_members',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post_children',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('parent_post_id', sa.BigInteger(), nullable=False),
    sa.Column('child_post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['child_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('post_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('posts', sa.Column('depth', sa.Integer(), nullable=False))
    op.drop_column('posts', 'tags')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('tags', mysql.JSON(), nullable=True))
    op.drop_column('posts', 'depth')
    op.drop_table('tags')
    op.drop_table('post_children')
    op.drop_table('group_members')
    # ### end Alembic commands ###
