"""Self referencing posts for comments

Revision ID: b266fb248311
Revises: 4d38a8bad655
Create Date: 2020-07-19 18:21:06.992907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b266fb248311'
down_revision = '4d38a8bad655'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('parent_post_id', sa.BigInteger(), nullable=True))
    op.create_foreign_key(None, 'posts', 'posts', ['parent_post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'parent_post_id')
    # ### end Alembic commands ###
