"""added social network version

Revision ID: eb94a471d96c
Revises: b491507e9191
Create Date: 2020-07-22 12:25:11.041576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb94a471d96c'
down_revision = 'b491507e9191'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socialnetwork_version',
    sa.Column('version', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socialnetwork_version')
    # ### end Alembic commands ###
